name: doinit
description: |
  Returns a JSON object containing an array of tags for the provided project

# Were we can define the inputs that our action will accept
inputs:
  github-repo:
    description: Github repo in the format 'owner/project'
    required: true
  github-max-tags:
    description: The maximum tags returned (default is 1)
    required: false
    default: "1"
  github-filter-tags:
    description: The filter for tags (ex. 3 for version 3 only)
    required: false
    default: "."

outputs:
  tags:
    description: 'The tag list for the specified project'
    value: ${{ steps.github-tags.outputs.tags }}

runs:
  using: "composite"
  steps:
    - id: github-tags
      shell: bash
      run: |
        TAGS=( $(curl --silent "https://api.github.com/repos/${{ inputs.github-repo }}/tags" | jq '.[] | .name' | awk '/^"${{ inputs.github-filter-tags }}/' | head -n ${{ inputs.github-max-tags }}) )
        echo "tags=$(jq -s '{tags: .}' <<< "${TAGS[@]}" | jq -c .)" >> $GITHUB_OUTPUT
